version: '3.8'

services:
  ma_postgres:
    image: postgres:13.4
    container_name: ma_postgres
    restart: always
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"

  ma_es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./volumes/elasticdb/:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  es_init:
    image: curlimages/curl:7.79.1
    container_name: es_init
    command: >
      sh -c "curl -XPUT -H 'Content-Type: application/json' -d@/usr/share/schemas_film.json es01:9200/movies &&
             curl -XPUT -H 'Content-Type: application/json' -d@/usr/share/schemas_genre.json es01:9200/genre &&
             curl -XPUT -H 'Content-Type: application/json' -d@/usr/share/schemas_person.json es01:9200/person"
    volumes:
      - ./postgres_to_es/schemas_es/schemas_film.json:/home/curl_user/schemas_film.json
      - ./postgres_to_es/schemas_es/schemas_genre.json:/home/curl_user/schemas_genre.json
      - ./postgres_to_es/schemas_es/schemas_person.json:/home/curl_user/schemas_person.json
    depends_on:
      - ma_es01
    profiles:
      - init

  ma_redis:
    image: 'redis:6.2.6'
    container_name: ma_redis
    ports:
      - '6379:6379'

  ma_etl:
    container_name: ma_etl
    build: ./postgres_to_es
    restart: unless-stopped
    depends_on:
      - ma_postgres
      - ma_es01
    env_file:
      - .env
    volumes:
      - ./volumes/ETL/etl.log:/sites/etl.log
      - ./volumes/ETL/:/sites/states/

  ma_fastapi:
    build: src/
    container_name: ma_fastapi
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    logging:
      options:
        max-size: 50m
